### ISSUE TITLE
[손노트] 8쪽 큐 설명 부분

### ISSUE THREAD

**Issue by Canine89** [dremdeveloper/codingtest_python#5]
# 그림 수정
rear와 front의 역할이 반대로 되어 있습니다.
![image](https://github.com/dremdeveloper/codingtest_python/assets/16553217/7909a53b-a2a3-4096-8c07-7e31543962cf)
추후 개정판 작업 시 반대로 그려서 다시 만들어 올리겠습니다. 
정오표에만 반영해 주시면 감사하겠습니다.

**Comment by dremdeveloper** [comment]
반영 완료했습니다. 감사합니다.
